### PR TITLE
Updated to JTS 1.15.1

### PR DESCRIPTION
**Pull request by jnh5y**
Changes to remove dependency on JTS-Examples and to allow for Windows test builds.

Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
Jody and I are still testing these PRs.  They may not be ready to merge yet.

**Comment by aaime** [comment]
I had a look and did not see anything problematic, we'll wait for all the PRs to be in a mergeable state on all projects.

**Comment by aaime** [comment]
Build failed, cannot find JTS 1.15.1 in repos. Kicking it again.

**Comment by jnh5y** [comment]
@aaime thanks for kicking the build!  I just got JTS 1.15.1 synced up to Maven Central a bit ago...

**Comment by aaime** [comment]
So we created a new 1.0.x branch, and we'll have to take on extra release and maintenance cost for around a year because of that (every time we need a fix, it's going to be merge on master, backport on 1.0.x, do two releases instead of one).
Merging this one on master only.

**Pull request merged**
