### PR TITLE
Upgrade to JTS 1.17.0

### PR DESCRIPTION
**Pull request by jnh5y**
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by aaime** [comment]
Looks good I guess? Is everything building fine downstreams? If so, we can do a release.

**Comment by jnh5y** [comment]
@aaime yes.  An initially round of downstream builds worked for me (using mvn clean install).  

Is there a better way for me to test the builds?

**Comment by aaime** [comment]
@jnh5y if you built geotools with "-Dall" and geoserver with "-Prelease" then we should be good. 
For extra credits, go into the geoserver community section and build with "-PcommunityRelease -DskipTests".

**Comment by jnh5y** [comment]
@aaime I'll try that locally here in a bit.

**Comment by dromagnoli** [comment]
> @aaime I'll try that locally here in a bit.

@jnh5y Great! I'll start the release as soon as you are done with that.

**Comment by jnh5y** [comment]
@aaime @dromagnoli ok, running 'mvn clean install' on GT/GWC/GS did work for me.  GT with 'mvn clean install -Dall' is showing that 'flatgeobuf' is going to need to be updated to the latest JTS. 

I'll sort that out and verify that I can build GT with a snapshot of that project.

**Comment by aaime** [comment]
The profiles/params I've mentioned are the ones used by the build server, we should probably make them the defaults.

**Comment by jnh5y** [comment]
Ok, an as update, the PR here: https://github.com/bjornharrtell/flatgeobuf/pull/65 gets the full GT build to go.  I'll ping Bjorn about that release.

**Comment by jnh5y** [comment]
@aaime @dromagnoli ok, I've managed to build GT/GWC/GS locally with full builds on JDK 8.  That did turn needs for flatbufgeo and java-vector-tiles to be updated as well.  I'm using https://github.com/geotools/geotools/pull/3034 to track progress overall.

I think this should be a green light for cutting the jai-ext upgrade and release.  I'm seeing jai-ext do what the unit tests in GT/GWC/GS say it should!

**Comment by dromagnoli** [comment]
@jnh5y 
Merged.
i'm going to do the release right now (I'll notice you when finished)
You might need to update the version of jai-ext on GT/GS/GWC poms accordingly

**Comment by dromagnoli** [comment]
@jnh5y

Release done.
https://maven.geo-solutions.it/it/geosolutions/jaiext/jaiext/1.1.16/jaiext-1.1.16.pom

**Comment by jnh5y** [comment]
@dromagnoli thanks!  I've updated the PRs with this version.  I'm rebuilding locally to double-check things.  I'll shout if there are any issues.

**Pull request merged**
